### ISSUE TITLE
numba version issue

### ISSUE THREAD

**Issue by tirohia** [Oshlack/ALLSorts#11]
More of a notification rather than an issue. 

Have recently been trying to install allsorts. Following the install instructions yielded the following when attempting to run the test scenario. 
```
Traceback (most recent call last):                                                                                                                    
  File "/home/cciamr.local/bcurran/bin/miniconda3/envs/allsorts/lib/python3.8/site-packages/numba/core/errors.py", line 744, in new_error_context     
    yield                                                                                                                                             
  File "/home/cciamr.local/bcurran/bin/miniconda3/envs/allsorts/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block         
    self.lower_inst(inst)                                                                                                                             
  File "/home/cciamr.local/bcurran/bin/miniconda3/envs/allsorts/lib/python3.8/site-packages/numba/core/lowering.py", line 328, in lower_inst          
    self.storevar(val, inst.target.name)                                                                                                              
  File "/home/cciamr.local/bcurran/bin/miniconda3/envs/allsorts/lib/python3.8/site-packages/numba/core/lowering.py", line 1278, in storevar           
    raise AssertionError(msg)                                                                                                                         
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32 
```
Problem appears to have been fixed by reverting numba to version 0.52.0 from 0.53.1

**Comment by jrboyd** [comment]
I just had the same issue and found the same fix.
