### ISSUE TITLE
Unable to run the automated pipeline with fastq files

### ISSUE THREAD

**Issue by ChengHsiangLu** [Oshlack/ALLSorts#13]
Hi, 
I'm new to the bioinformatics field and I encountered errors that I don't know how to solve it. I've followed the Installation steps and run the test successfully. 
[https://github.com/Oshlack/ALLSorts/wiki/1.-Installation](https://github.com/Oshlack/ALLSorts/wiki/1.-Installation?fbclid=IwAR2FFSdV057Usz1XeqBkz_IJpl0PMcVfGOiFjAyQ_iQU8P-ogCiLhAs7Hus)

I've also. installed Bpipe, STAR, and samtools. Then, I set environmental variables for executables.

However, when I tried to follow the automated pipeline starting with FASTQ files and put two fastq.gz files in /home/ec2-user/ALLSorts/tests/fastq/ directory, it showed errors. This is the code I used:

"(allsorts) [ec2-user@ip-10-242-22-113 ALLSorts]$ bpipe -p results=/data/ALLSorts_new/test_results -p threads=16 -p a_mem=122000000000 -p type="fastq" -p strand="no" -p format="/%_.fastq.gz" -p genome_dir="/data/ALLSorts_new/ALLSorts_files" /data/ALLSorts_new/ALLSorts/tools/counts/counts.groovy /home/ec2-user/ALLSorts/tests/fastq/*.fastq.gz"

MSG: vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
MSG:     NOTE: Pipeline completed as process 18958.  Trailing lines follow.
MSG:     Use bpipe log -n <lines> to see more lines
MSG: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

╒══════════════════════════════════════════════════════════════════════════════════════════════════╕
|                              Starting Pipeline at 2022-09-22 23:50                               |
╘══════════════════════════════════════════════════════════════════════════════════════════════════╛

========================================== Stage make_dir ==========================================
WARNING: An error occurred evaluating your pipeline stage: groovy.lang.MissingPropertyException: No such property: single in stage make_dir. Please see Bpipe log file for full details.
=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

                             No such property: single in stage make_dir

Please see the details below for more information.

========================================== Error Details ===========================================

groovy.lang.MissingPropertyException: No such property: single in stage make_dir
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at counts.groovy$_run_closure1$_closure10.doCall(counts.groovy:90)
        at counts.groovy$_run_closure1$_closure10.doCall(counts.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at counts.groovy$_run_closure1.doCall(counts.groovy:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at counts.groovy.run(counts.groovy:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

====================================================================================================

More details about why this error occurred may be available in the full log file .bpipe/bpipe.log

I found someone who had a similar issue to this. 
https://github.com/Oshlack/Slinker/issues/2

Nevertheless, I reinstalled everything and tried but still got this error message. What can I do to solve this error? Thank you.

Best,
Sam

**Comment by norberto-sanchez** [comment]
Did you resolve the error?  I am trying to run the algorithm but I have the same issue.
