### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by hanxuelian** [Oshlack/ALLSorts#4]
ALLSorts can run successfully with test data, but an error is reported with my own test data. The details are as follows.

1)inputfile(reads count on each gene)
,hezhiyan,LIANGXIAOLAN,LIAOJIFENG,lilingyi,LXINZHE,NGR200625001,qianli,qinpeixiang,luozhimin,luoyangying,huangzhegnhan,chenziyang,zhuxiangyan,zhaojinsheng,qinzuofa,huanglianbin,xuxunjia,xuyongyi,ZYZ
DSC3,0,0,0,0,4,1,1,0,0,0,7,7,0,0,0,0,0,1,0
IGF2BP1,1,0,0,0,37,0,0,0,0,0,1,4,0,0,0,0,0,0,0
KCNK3,0,0,9,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
IGJ,0,9,0,0,0,10,0,88,1,8,7,2,0,4,0,0,0,0,0
PTPRM,0,0,12,14,1,1,1,1,0,4,4,8,3,0,1,0,0,0,0
KCNN1,0,0,0,1,23,0,1,1,2,23,5,70,0,1,0,0,2,5,0
CD99,8,0,0,0,9,125,0,109,504,301,979,86,486,88,219,267,5,6,2
HAP1,0,1,0,0,13,5,0,1,1,4,4,1,0,0,0,0,0,0,2
AGAP1,0,0,13,16,1,1,1,8,0,11,79,0,0,0,0,0,0,1,1
CHST2,1,6,207,85,1,9,10,177,0,30,9,14,2,47,25,4,0,7,0
SLC2A5,0,0,0,0,0,35,0,5,48,28,230,22,114,60,26,6,2,0,0
IFITM1,0,1,2,0,0,13,5,203,168,310,75,52,97,9,145,24,4,12,0
ABHD3,0,2,0,1,13,2,0,7,1,10,22,28,5,2,2,3,2,3,5
PCLO,2,6,1,0,23,1,4,0,8,7,16,70,1,0,0,0,0,7,2
TNS1,0,0,0,0,0,13,0,408,29,55,158,9,10,10,3,4,0,1,1
NCF2,5,0,2,4,8,21,4,83,44,200,89,26,17,21,177,25,9,14,4
MIB1,0,0,0,4,1,12,0,20,20,3,84,26,7,2,4,5,0,2,0
TCFL5,6,1,11,26,6,18,3,26,78,27,288,291,94,27,50,28,0,0,0
ARHGEF4,7,10,108,2,3,0,2,8,0,10,1,16,1,1,0,1,0,4,6
RGMA,0,0,0,0,4,0,1,10,0,4,1,3,2,0,0,0,0,0,0

2)command line
python ALLSorts -samples gene.forRF.classifier.HTseqCount.xls -destination test/

3)Error
=======================================================================
Prediction Mode
=======================================================================
Loading classifier...
Saving predictions...
Traceback (most recent call last):
  File "/home/hanxl/Software/anaconda3/envs/allsorts/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hanxl/Software/anaconda3/envs/allsorts/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ALLSorts/__main__.py", line 20, in <module>
    allsorts.run()
  File "ALLSorts/allsorts.py", line 90, in run
    probabilities = allsorts_clf.predict_proba(ui.samples, parents=ui.parents)
  File "ALLSorts/pipeline.py", line 115, in predict_proba
    Xt = transform.transform(Xt)
  File "ALLSorts/stages/preprocessing.py", line 108, in transform
    counts = self.normalise.transformMor(counts.transpose()).transpose()
  File "/home/hanxl/TEST/ExpressionProfile/LIMINGZE/ph-like_method/AllSorts/tools/MoRP/morp/morp.py", line 122, in transformMor
    counts_normalised, success = self._applyMor(counts, step_3_logs, self.gm)
  File "/home/hanxl/TEST/ExpressionProfile/LIMINGZE/ph-like_method/AllSorts/tools/MoRP/morp/morp.py", line 102, in _applyMor
    gene_check = step_3_logs.index[0]
  File "/home/hanxl/Software/anaconda3/envs/allsorts/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3929, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by breons** [comment]
MoRP is no longer used in ALLSorts for future reference.
