### ISSUE TITLE
First test failed

### ISSUE THREAD

**Issue by vipmak** [Oshlack/ALLSorts#6]
Hi, thanks for you great work, we are also doing an ALL classifier but we are using very simple algorithms so I'm hoping to use your tool to make sure our models are not too far off from more sophisticated approaches. However, I have not been able to complete the test (I'm not familiar with Python + Anaconda). It looks like something fails in the Python code but I can't tell what.

Any help is greatly appreciated!

Here's as far as I got:

(base) [Linus ~]$ cd .vipmak/ALLSorts/
(base) [Linus ALLSorts]$ conda activate allsorts
(allsorts) [Linus ALLSorts]$ mkdir test_results
(allsorts) [Linus ALLSorts]$ ls
ALLSorts  counts  Dockerfile  env  LICENSE  MANIFEST.in  README.md  setup.py  test_results  tests  tools
(allsorts) [Linus ALLSorts]$ python ALLSorts -samples tests/counts/test_counts.csv -destination test_results
Traceback (most recent call last):
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/errors.py", line 776, in new_error_context
    yield
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 235, in lower_block
    self.lower_inst(inst)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 380, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 556, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 1084, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 815, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 1055, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/base.py", line 1194, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/base.py", line 1224, in wrapper
    return fn(*args, **kwargs)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/cpython/rangeobj.py", line 40, in range1_impl
    state.stop = stop
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/cgutils.py", line 164, in __setattr__
    self[self._datamodel.get_field_position(field)] = value
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/cgutils.py", line 188, in __setitem__
    raise TypeError("Invalid store of {value.type} to "
TypeError: Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f700734ca90> (trying to write member #1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vipmak/.conda/envs/allsorts/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vipmak/.conda/envs/allsorts/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ALLSorts/__main__.py", line 13, in <module>
    import allsorts
  File "ALLSorts/allsorts.py", line 32, in <module>
    from ALLSorts.operations.comparisons import rebuild_comparisons
  File "/home/vipmak/.local/lib/python3.8/site-packages/ALLSorts/operations/comparisons.py", line 20, in <module>
    from umap import UMAP
  File "/home/vipmak/.local/lib/python3.8/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/home/vipmak/.local/lib/python3.8/site-packages/umap/umap_.py", line 54, in <module>
    from umap.layouts import (
  File "/home/vipmak/.local/lib/python3.8/site-packages/umap/layouts.py", line 39, in <module>
    def rdist(x, y):
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/decorators.py", line 226, in wrapper
    disp.compile(sig)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 979, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 141, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 155, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 168, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 686, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 428, in compile_extra
    return self._compile_bytecode()
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 492, in _compile_bytecode
    return self._compile_core()
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 471, in _compile_core
    raise e
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 462, in _compile_core
    pm.run(self.state)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 396, in run_pass
    lower.lower()
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 138, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 192, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 221, in lower_function_body
    self.lower_block(block)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 235, in lower_block
    self.lower_inst(inst)
  File "/home/vipmak/.conda/envs/allsorts/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/vipmak/.local/lib/python3.8/site-packages/numba/core/errors.py", line 786, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f700734ca90> (trying to write member #1)

File "../../.local/lib/python3.8/site-packages/umap/layouts.py", line 53:
def rdist(x, y):
    <source elided>
    dim = x.shape[0]
    for i in range(dim):
    ^

During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, target=None)" at /home/vipmak/.local/lib/python3.8/site-packages/umap/layouts.py (53)

(allsorts) [Linus ALLSorts]$ uname -a
Linux Linus 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by breons** [comment]
Hi! 

Thanks for trying ALLSorts, apologies for the hurdle at the very first step! Let's get it working.

I'd be really keen to see how you go! I would try using the automated pipelines to get the best out of ALLSorts:
- https://github.com/Oshlack/ALLSorts/wiki/2.1.-Automated-Pipeline---Starting-with-FASTQ-or-FASTA-files or
- https://github.com/Oshlack/ALLSorts/wiki/2.2.-Automated-Pipeline---Starting-with-BAM-files

It looks like it has something to do with the UMAP import. Could you please do a:

`conda list`

After you've entered the conda environment? i.e. `conda activate allsorts`

Cheers,
Breon.

**Comment by vipmak** [comment]
Thanks Breon for the quick reply! The listing is attached.


We are using more or less the same datasets here as you used so I should be able to replicate the results. I'm far downstream from the sequencer so I am using tab-delimited text files of raw reads as the input format, but I can ask for the other types if they contain additional useful information.


Cheers,


Ville


________________________________

**Comment by breons** [comment]
No worries, Ville, keen to get you up and running.

Oh cool! We also have the counts used in this repo as well. I'd be interested to see how potentially different formats change the classification. 
`https://github.com/Oshlack/ALLSorts/tree/master/counts`

So a difference that I see is that a newer version of "numba" has been installed. Hopefully, it's as simple as doing this when in your environment:

`conda install numba=0.50.1`

If so, great! I'll add it as a dependency. If not, I'll rip out that UMAP requirement as it's not necessary at the moment and I can spend some time testing it more robustly.

Either way, let me know :).
Breon.

**Comment by vipmak** [comment]
Hi Breon, I tried the trick but it did not work, still the same error. I also re-installed anaconda and ALLSorts, but still the same result. I attached the list again with the error report pasted in the same file.


I downloaded the ALLSorts code using the command

"git clone https://github.com/Oshlack/ALLSorts.git"


Anaconda version is

conda 4.10.3


I'm using Ubuntu 20.04.3 LTS so it is a fairly recent distro (5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux). I installed everything as a regular user rather than the root. Maybe you can reproduce the same issue at your end?


I also noticed that the allsorts env is using python 3.8.3 while the base has 3.8.8. I also installed the latest python 3.9 but the modules were not linked so it would not run. Not sure if any of this matters.


Any ideas what to try next?


Ville


________________________________

**Comment by breons** [comment]
Hi Ville,

Ok, I've removed the UMAP feature in a development branch for you to trial:
[dev-0.2.1](https://github.com/Oshlack/ALLSorts/tree/dev-0.2.1)

So if you could try doing the following in your ALLSorts clone directory whilst being in your new ALLSorts environment:
- `git pull`
- `git checkout dev-0.2.1`
- `pip install .`
- Then re-run the test. 

Hopefully that get's you up and running!

>  I'm far downstream from the sequencer so I am using tab-delimited text files of raw reads as the input format

Just picked up on this! I'm yet to put in a check for tab-delimited formats, so for the time being please convert to a CSV with genes in columns and samples in rows.

Cheers,
Breon.

**Comment by vipmak** [comment]
OK, GitHub have screwed up their certificates, I can't even access their web page anymore. So I'll get back to you some time maybe next week when I have more time and once these issues are hopefully resolved and I can update the code.?


Ville

________________________________

**Comment by vipmak** [comment]
Success! The example ran through and produced figures. Sorry for the delay, I had other projects to work in the meantime.


Thanks for your help, I will run our data through ALLSorts at some point in the coming weeks when my other commitments allow. If you are interested in seeing the results, I can share them outside the GitHub message, please contact me directly at my SAHMRI email (ville-petteri.makinen) as this is no longer about debugging.


Cheers,


Ville


________________________________

**Comment by breons** [comment]
Great! I'll be sure to reach out and see how you went (and how ALLSorts faired!).
